databases:
  - name: In100gram
    databaseName: in100gram_db
    user: in100gram_user

services:
  - type: web
    name: In100gram
    plan: free
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "cd in100gram/ && gunicorn in100gram.wsgi:application"
    
